### ISSUE TITLE
Do you have an example capture file?

### ISSUE THREAD

**Issue by hadrielk** [htbegin/lua_wireshark#1]
Hi,
I'd like to add your Lua plugin script to Wireshark's repository (I'm one of the developers).
Do you have an example packet capture to use with the script, that you would be willing to have publicly viewable?
-hadriel

**Comment by htbegin** [comment]
Sorry, I don't have an example capture on my hand. Maybe I could try to handcraft such packets.

**Comment by hadrielk** [comment]
No don't worry about it - it was more of a nice-to-have than anything.  Your Lua plugin is in the repository here:
https://wiki.wireshark.org/Contrib
